In [1]:
def batch(iterable, n=1):
    l = len(iterable)
    for ndx in range(0, l, n):
        yield iterable[ndx:min(ndx + n, l)]
        

In [2]:
import numpy as np

In [3]:
a = np.array([ [[1,1,1,1]], [[2,2,2,2]] ,[[3,3,3,3]] , [[4,4,4,4]]])

In [12]:
max(1,2)

2

In [11]:
for bat in batch(range(len(a)), 2):
    print(bat)
    print(a[bat])
    print()

range(0, 2)
[[[1 1 1 1]]

 [[2 2 2 2]]]

range(2, 4)
[[[3 3 3 3]]

 [[4 4 4 4]]]



In [17]:
import threading

class threadsafe_iter:
    """Takes an iterator/generator and makes it thread-safe by
    serializing call to the `next` method of given iterator/generator.
    """
    def __init__(self, it):
        self.it = it
        self.lock = threading.Lock()

    def __iter__(self):
        return self

    def next(self):
        with self.lock:
            return self.it.next()

In [18]:
def threadsafe_generator(f):
    """A decorator that takes a generator function and makes it thread-safe.
    """
    def g(*a, **kw):
        return threadsafe_iter(f(*a, **kw))
    return g

In [19]:
@threadsafe_generator
def count():
    i = 0
    while True:
        i += 1
        yield i

In [24]:
for i in count():
    print(i)

TypeError: iter() returned non-iterator of type 'threadsafe_iter'